
hem = { '1' : 'left',
        '2' : 'left', 
        '3' : 'left', 
        '4' : 'left', 
        '5' : 'left', 
        '6' : 'left', 
        '7' : 'left', 
        '8' : 'left', 
        '9' : 'left', 
        '10' : 'right', 
        '11' : 'right', 
        '12' : 'right', 
        '13' : 'right', 
        '14' : 'right', 
        '15' : 'right', 
        '16' : 'right', 
        '17' : 'right', 
        '18' : 'right'}
 
ROI = { '1' : 'dorsal occipital',
        '2' : 'dorsal occipital',
        '3' : 'posterior fusiform gyrus',
        '4' : 'medial fusiform gyrus',
        '5' : 'medial fusiform gyrus',
        '6' : 'intraparietal sulcus',
        '7' : 'mid-occipital gyrus',
        '8' : 'inferior temporal gyrus',
        '9' : 'intraparietal sulcus',
        '10' : 'intraparietal sulcus',
        '11' : 'posterior fusiform gyrus',
        '12' : 'medial fusiform gyrus',
        '13' : 'dorsal occipital',
        '14' : 'dorsal occipital',
        '15' : 'medial fusiform gyrus',
        '16' : 'intraparietal sulcus',
        '17' : 'mid-occipital gyrus',
        '18' : 'inferior temporal gyrus'}

sens ={ '1' : 'chair',
        '2' : 'house', 
        '3' : 'house', 
        '4' : 'house', 
        '5' : 'chair', 
        '6' : 'house', 
        '7' : 'chair', 
        '8' : 'chair', 
        '9' : 'chair', 
        '10' : 'house', 
        '11' : 'house', 
        '12' : 'house', 
        '13' : 'house', 
        '14' : 'chair', 
        '15' : 'chair', 
        '16' : 'chair', 
        '17' : 'chair', 
        '18' : 'chair'}


ROIids  = { 'dorsal occipital'              :   [1, 2, 13, 14],
            'posterior fusiform gyrus'      :   [3, 11],
            'medial fusiform gyrus'         :   [4, 5, 12, 15],
            'intraparietal sulcus'          :   [6, 9, 10, 16],
            'mid-occipital gyrus'           :   [7, 17],
            'inferior temporal gyrus'       :   [8, 18]}
